Store/StoreApp/Models/ErrorViewModel.cs
using System;

namespace StoreApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Store/StoreApp/Models/QuantityByBookTitle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreApp.Models
{
    public class QuantityByBookTitle
    {
        public string BookTitle { get; set; }

        public int Quantity { get; set; }
    }
}

Store/StoreApp/Controllers/BookInventoryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using InventoryManager.Service.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Models;

namespace StoreApp.Controllers
{
    public class BookInventoryController : Controller
    {
        private IInventoryManagerService inventoryService;

        private const string UPLOAD_FILE_BAD_REQUEST_MSG = "Must specify valid file information";

        public BookInventoryController(IInventoryManagerService inventoryService)
        {
            this.inventoryService = inventoryService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadFile(IList<IFormFile> files)
        {
            if(files == null || files.Count == 0 || files.Any(file => file == null || file.Length == 0))
            {
                return BadRequest(UPLOAD_FILE_BAD_REQUEST_MSG);
            }

            try
            {
                var filesAsString = await Task.WhenAll(files.Select(file => ReadBookCatalogInfo(file)));

                await Task.WhenAll(filesAsString.Select(file => inventoryService.ImportBookInvenoryCatalog(file)));
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return Ok();
        }

        private async Task<string> ReadBookCatalogInfo(IFormFile file)
        {
            var bookCatalog = string.Empty;

            using (var reader = new StreamReader(file.OpenReadStream()))
            {
                bookCatalog = await reader.ReadToEndAsync();
            }

            return bookCatalog;
        }

        [HttpGet]
        public async Task<IActionResult> GetBookQuantity(string bookIdentifier)
        {
            if (string.IsNullOrEmpty(bookIdentifier))
            {
                return BadRequest("Must specify identifier for book");
            }

            string[] bookInfo = Regex.Split(bookIdentifier, Utils.Constants.BookIdentifierSplitRegex);

            if (bookInfo.Length != 2 || bookInfo.Any(bi => string.IsNullOrWhiteSpace(bi)))
            {
                return BadRequest("Book identifier in not in the correct format");
            }

            int quantity = 0;

            try
            {
                quantity = await inventoryService.ReturnQuantityByBookTitle(bookInfo[1], bookInfo[0]);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return Ok(new QuantityByBookTitle()
            {
                BookTitle = bookIdentifier,
                Quantity = quantity
            });
        }

        [HttpGet]
        public async Task<IActionResult> CalculateBasketPrice(string rawBookBasketList)
        {
            if (string.IsNullOrEmpty(rawBookBasketList))
            {
                return BadRequest("Must specify raw book basket list");
            }

            string[] basketBookList = Regex.Split(rawBookBasketList, Utils.Constants.BookBasketEntriesSplitRegex);

            if (basketBookList.Length == 0 || basketBookList.Any(bi => string.IsNullOrWhiteSpace(bi)))
            {
                return BadRequest("Basket list is not in the correct format");
            }

            decimal price = 0;

            try
            {
                price = await inventoryService.CalculateBookBasketPrice(basketBookList);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return Ok(price);
        }
    }
}

Store/StoreApp/Controllers/HomeController.cs
using System.Diagnostics;
using InventoryManager.Service.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Models;

namespace StoreApp.Controllers
{
    public class HomeController : Controller
    {
        private IInventoryManagerService inventoryService;

        public HomeController(IInventoryManagerService inventoryService)
        {
            this.inventoryService = inventoryService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {

            return View();
        }

        public IActionResult Contact()
        {

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Store/StoreApp/Views/BookInventory/Index.cshtml

@{
    ViewData["Title"] = "Book Inventory";
}

<h3>Book Inventory</h3>

<br />
<br />

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <form asp-controller="BookInventory" asp-action="UploadFile"
              data-ajax="true"
              data-ajax-method="POST"
              data-ajax-success="onSuccessfulFileUploads"
              data-ajax-failure="onFail"
              enctype="multipart/form-data">

            <div class="form-group">
                <div class="col-md-12">
                    <p>Upload Book Catalogs:</p>
                    <input class="form-control" type="file" name="files" multiple />
                    <button class="btn btn-primary" type="submit">Upload</button>
                </div>
            </div>
            @Html.AntiForgeryToken()
        </form>
    </div>
</div>

<br />
<br />

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">Check number of available copies:</div>
            <div class="panel-body">
                <form asp-action="GetBookQuantity" asp-controller="BookInventory"
                      data-ajax="true"
                      data-ajax-method="GET"
                      data-ajax-failure="onFail"
                      data-ajax-success="onSuccessfulBookQuantityReturn">

                    <div class="form-group">
                        <div class="col-md-12">
                            <input class="form-control" type="text" name="bookIdentifier" placeholder="Book Author - Book Title">
                            <input class="btn btn-primary" type="submit" value="Get Book Quantity">
                        </div>
                    </div>
                </form>
            </div>

            <table class="table" id="bookQuantityList">
                <tr>
                    <th>Book Title</th>
                    <th>Quantity</th>
                </tr>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

<br />
<br />

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">Calculate basket price: <span id="basketPrice"></span></div>
            <div class="panel-body">
                <form asp-action="CalculateBasketPrice" asp-controller="BookInventory"
                      data-ajax="true"
                      data-ajax-method="GET"
                      data-ajax-failure="onFail"
                      data-ajax-success="onSuccessfulBookBasketPriceCalculation">

                    <div class="form-group">
                        <div class="col-md-12">
                            <textarea id="bookBucket" class="form-control" type="text" name="rawBookBasketList" style="height: 250px;" placeholder="(Book Author - Book Title) , (Book Author - Book Title) ..."></textarea>
                            <input class="btn btn-primary" type="submit" value="Calculate">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script>
        var onSuccessfulFileUploads = function() {
            alert("Successful file uploads.");
        }

        var onSuccessfulBookQuantityReturn = function (data) {
            $('#bookQuantityList').show();
            $('#bookQuantityList > tbody:last-child').append("<tr><td>" + data.bookTitle + "</td><td>" + data.quantity  + "</td></tr>");
        }

        var onSuccessfulBookBasketPriceCalculation = function (data) {
            alert(data);
            $('#basketPrice').text(data);
        }

        var onFail = function (data, d1, d2) {
            alert(data.responseText);
        }
    </script>
}

Store/StoreApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>

<h4>A bookstore wants to develop a new computer tool to:</h4>
<ul>
    <li>
        Import information from its stock
    </li>
    <li>
        Get information about a particular book
    </li>
    <li>
        Calculate the price of a basket of books
    </li>
</ul>
<br/>
<p>
    You are in charge of the development of this tool whose functionalities are detailed below. You are requested to implement the different methods exposed by the interface described in Appendix 4, following the specifications below.
</p>

Store/StoreApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>

<address>
    Nadya Hristova<br />
    Sofia, Bulgaria<br />
    <abbr title="Phone">P:</abbr>
    +359 89 7575 094
</address>

<address>
    <strong>Support:</strong> <a href="mailto:nadia.geo.hristova@gmail.com">nadia.geo.hristova@gmail.com</a><br />
</address>

Store/StoreApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h4>Home Page</h4>

Store/StoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StoreApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">StoreApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - StoreApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>